# Generated by Django 3.2 on 2023-07-31 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
